title: DJ Notes
description: DDJ-FLX4 完整教程 · 边学边写
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: "topics"
    values:
      layout: lesson
  - scope:
      path: "notes"
    values:
      layout: page
